### ISSUE TITLE
Checklist of features of CMS version 1.0

### ISSUE THREAD

**Issue by RChaubey16** [Libbna/CUSTOM-CMS#212]
### Features included in version 1.0 of custom CMS : 

- [x] User authentication.
- [x] Allow authenticated users to add contents like articles and blocks
- [x] Provide a single pre-defined theme.
- [x] Admin UI
- [x] Allow admin to change role of authenticated users.
- [x] Allow admin to add and delete users.
- [x] Allow admin to add custom logo and sitename.
